"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Activity, Bell, FileText, Plus, RefreshCw, Search, Sparkles, X, ExternalLink } from "lucide-react";
import { browserClient } from "../lib/supabase";

const supabase=browserClient();
async function api(url:string,options:RequestInit={}){
  const {data:{session}}=await supabase.auth.getSession();
  return fetch(url,{...options,headers:{...options.headers,Authorization:`Bearer ${session?.access_token||""}`},cache:"no-store"});
}

type Company = {symbol:string;name:string};
type Filing = {id:string;symbol:string;category:string;title:string;description:string;url:string;published_at:string;analysis:string|null;document_read:number;read_at:string|null};
type Note = {sentiment:string;materiality:string;summary:string;reasoning:string;uncertainties:string;evidence:string;analyzedAt:string};
type Dashboard = {watchlist:Company[];filings:Filing[];feed:{last_checked_at:string;status:string}|null;members:{email:string;role:string;telegram_chat_id:string|null;email_alerts:boolean;telegram_alerts:boolean}[];deliveries:{filing_id:string;channel:string;status:string;attempted_at:string;error:string|null}[];account:string};
const fmt=(s?:string|null)=>s?new Intl.DateTimeFormat("en-IN",{timeZone:"Asia/Kolkata",day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(s)):"—";
const note=(s:string|null):Note|null=>{try{return s?JSON.parse(s):null}catch{return null}};
const headline=(f:Filing)=>f.description?.split("|SUBJECT:")[0]?.trim()||f.title;

export default function Home(){
  const [sessionReady,setSessionReady]=useState(false),[signedIn,setSignedIn]=useState(false),[email,setEmail]=useState(""),[signing,setSigning]=useState(false),[invitation,setInvitation]=useState("");
  const [chatId,setChatId]=useState(""),[emailAlerts,setEmailAlerts]=useState(true),[telegramAlerts,setTelegramAlerts]=useState(false),[settingsLoaded,setSettingsLoaded]=useState(false);
  const [data,setData]=useState<Dashboard|null>(null),[error,setError]=useState(""),[message,setMessage]=useState(""),[query,setQuery]=useState(""),[selected,setSelected]=useState("all"),[active,setActive]=useState<Filing|null>(null),[busy,setBusy]=useState(""),[loading,setLoading]=useState(true);
  const [companyResults,setCompanyResults]=useState<[string,string][]>([]);
  const baseline=useRef<Set<string>|null>(null);
  const attempted=useRef<Set<string>>(new Set());
  const load=useCallback(async(quiet=false)=>{
    if(!quiet)setLoading(true);
    try{
      const r=await api("/api/dashboard"),v=await r.json() as any;
      if(!r.ok)throw new Error(v.error||"Could not load dashboard");
      const next=v as Dashboard,ids=new Set(next.filings.map(f=>f.id));
      if(baseline.current){const incoming=next.filings.filter(f=>!baseline.current?.has(f.id));if(incoming.length){setMessage(`${incoming.length} filing${incoming.length===1?"":"s"} added to your watchlist`);const fresh=incoming.find(f=>Date.parse(f.published_at)>Date.now()-5*60000);if(fresh&&typeof Notification!=="undefined"&&Notification.permission==="granted")new Notification("New NSE filing",{body:`${fresh.symbol}: ${headline(fresh)}`})}}
      baseline.current=ids;setData(next);setError("");
    }catch(e){setError(e instanceof Error?e.message:"Dashboard unavailable")}finally{setLoading(false)}
  },[]);
  useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSignedIn(!!data.session);setSessionReady(true)});const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>{setSignedIn(!!session);if(session)load()});return()=>subscription.unsubscribe()},[load]);
  useEffect(()=>{if(!signedIn)return;load();const timer=setInterval(()=>load(true),30000);return()=>clearInterval(timer)},[load,signedIn]);
  useEffect(()=>{const own=data?.members?.find(m=>m.email===data.account);if(own&&!settingsLoaded){setChatId(own.telegram_chat_id||"");setEmailAlerts(own.email_alerts);setTelegramAlerts(own.telegram_alerts);setSettingsLoaded(true)}},[data,settingsLoaded]);
  useEffect(()=>{if(query.trim().length<2){setCompanyResults([]);return}const controller=new AbortController(),timer=setTimeout(()=>{api(`/api/companies?q=${encodeURIComponent(query)}`,{signal:controller.signal}).then(r=>r.json()).then((v:any)=>setCompanyResults(v.results||[])).catch(()=>{})},250);return()=>{clearTimeout(timer);controller.abort()}},[query]);
  useEffect(()=>{
    const pending=data?.filings.find(f=>!f.analysis&&!attempted.current.has(f.id));
    if(!pending)return;
    attempted.current.add(pending.id);
    api("/api/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:pending.id})})
      .then(r=>r.json()) .then((v:any)=>{if(v.status==="complete")load(true);if(v.status==="key_required")data?.filings.forEach(f=>attempted.current.add(f.id))}).catch(()=>{});
  },[data,load]);
  const filtered=useMemo(()=>(data?.filings||[]).filter(f=>selected==="all"||f.symbol===selected),[data,selected]);
  const recent=filtered;
  const analyzed=recent.map(f=>note(f.analysis)).filter((x):x is Note=>!!x);
  const positive=analyzed.filter(n=>n.sentiment==="positive").length,negative=analyzed.filter(n=>n.sentiment==="negative").length;
  const suggestions=companyResults.filter(([s])=>!data?.watchlist.some(c=>c.symbol===s));
  const unread=(data?.filings||[]).filter(f=>!f.read_at).length;
  async function action(url:string,options:RequestInit,key:string){setBusy(key);setMessage("");try{const r=await api(url,options),v=await r.json() as any;if(!r.ok)throw new Error(v.error||"Request failed");await load(true);return v}catch(e){setMessage(e instanceof Error?e.message:"Request failed");return null}finally{setBusy("")}}
  async function add(symbol:string){if(await action("/api/watchlist",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({symbol})},symbol)){setQuery("");setSelected(symbol)}}
  async function remove(symbol:string){await action(`/api/watchlist?symbol=${encodeURIComponent(symbol)}`,{method:"DELETE"},symbol);if(selected===symbol)setSelected("all")}
  async function open(f:Filing){setActive(f);if(!f.read_at){await action("/api/alerts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:f.id})},"read");setActive({...f,read_at:new Date().toISOString()})}}
  async function analyze(f:Filing){const v=await action("/api/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:f.id})},f.id);if(v?.status==="key_required")setMessage("Groq analysis is waiting for a server-side API key.");if(v?.status==="complete")setActive({...f,analysis:JSON.stringify(v.analysis),document_read:v.documentRead?1:f.document_read})}
  async function signIn(e:React.FormEvent){e.preventDefault();setSigning(true);const {error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:window.location.origin}});setMessage(error?.message||"Check your email for a sign-in link.");setSigning(false)}
  if(!sessionReady)return <div className="shell"><main className="main">Loading SignalDesk…</main></div>;
  if(!signedIn)return <div className="shell"><header className="topbar"><div className="brand"><span className="brand-mark"><Activity size={20}/></span>Signal<span className="slash">/</span>Desk <small>NSE WATCH</small></div></header><main className="main auth-main"><span className="eyebrow">PRIVATE FAMILY WORKSPACE</span><h1>Watch the market<span>.</span></h1><p>Sign in with an invited email to follow NSE company filings.</p><form onSubmit={signIn} className="auth-form"><label htmlFor="email">Email address</label><input id="email" type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/><button disabled={signing}>{signing?"Sending link…":"Send sign-in link"}</button></form>{message&&<p role="status">{message}</p>}</main></div>;
  return <div className="shell">
    <header className="topbar"><div className="brand"><span className="brand-mark"><Activity size={20}/></span>Signal<span className="slash">/</span>Desk <small>NSE WATCH</small></div><div className="top-right"><span className="live-label"><i/> FILING MONITOR</span><button onClick={async()=>{if(typeof Notification==="undefined"){setMessage("Browser notifications are unavailable on this device.");return}const permission=await Notification.requestPermission();setMessage(permission==="granted"?"Browser alerts enabled while this page is open.":"Browser alerts were not enabled.")}} aria-label="Enable browser alerts" title="Enable browser alerts"><Bell size={18}/></button><button onClick={()=>load()} aria-label="Refresh filings"><RefreshCw size={18} className={loading?"spin":""}/></button><button onClick={()=>supabase.auth.signOut()} title="Sign out">Sign out</button><span className="avatar">HP</span></div></header>
    <div className="layout"><aside className="sidebar"><div className="side-label">YOUR WORKSPACE</div><button className="overview" onClick={()=>setSelected("all")}><Activity size={17}/> Overview <b>{data?.watchlist.length||0}</b></button><div className="side-title">WATCHLIST <button onClick={()=>document.getElementById("company-search")?.focus()} aria-label="Add company"><Plus size={17}/></button></div>{data?.watchlist.map(c=><div className={`side-company ${selected===c.symbol?"current":""}`} key={c.symbol}><button onClick={()=>setSelected(c.symbol)}><span className="monogram">{c.symbol.slice(0,2)}</span><span><strong>{c.symbol}</strong><small>{c.name}</small></span></button><button className="side-remove" onClick={()=>remove(c.symbol)} aria-label={`Remove ${c.name}`}><X size={14}/></button></div>)}{!data?.watchlist.length&&<p className="side-empty">Add companies to begin tracking.</p>}<div className="side-foot">Source linked to NSE filings</div></aside>
    <main className="main"><div className="heading"><div><span className="eyebrow">MARKET INTELLIGENCE / WATCHLIST</span><h1>Company signals<span>.</span></h1><p>Track exchange filings for the companies that matter to you.</p></div><button className="refresh" onClick={()=>load()}><RefreshCw size={16} className={loading?"spin":""}/> Refresh feed</button></div>
    <div className="stats"><div><span className="stat-icon"><FileText size={19}/></span><section><strong>{data?.watchlist.length??"—"}</strong><small>Companies tracked</small></section></div><div><span className="stat-icon purple"><Bell size={19}/></span><section><strong>{unread}</strong><small>Unread filings</small></section></div><div><span className="stat-icon blue"><RefreshCw size={19}/></span><section><strong>{fmt(data?.feed?.last_checked_at)}</strong><small>Last feed check · IST</small></section></div></div>
    <div className="section-title"><div><h2>Watchlist</h2><p>Choose companies to follow their published announcements.</p></div><small>{data?.watchlist.length||0} COMPANIES</small></div>
    <div className="search"><Search size={19}/><input id="company-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search company name or NSE symbol..." autoComplete="off"/><span>NSE EQUITIES</span>{query&&<div className="suggestions">{suggestions.length?suggestions.map(([s,n])=><button key={s} onClick={()=>add(s)} disabled={busy===s}><span className="monogram">{s.slice(0,2)}</span><span><strong>{n}</strong><small>{s} · NSE</small></span><Plus size={16}/></button>):<p>No match in the current company catalog.</p>}</div>}</div>
    <div className="chips">{data?.watchlist.map(c=><div className={`chip ${selected===c.symbol?"chosen":""}`} key={c.symbol}><button onClick={()=>setSelected(c.symbol)}>{c.symbol}</button><button onClick={()=>remove(c.symbol)} aria-label={`Remove ${c.symbol}`}><X size={13}/></button></div>)}{!data?.watchlist.length&&<span className="placeholder">Your selected companies will appear here</span>}</div>
    {!!data?.watchlist.length&&<div className="pulse-card"><div><span className="eyebrow">RECENT FILING PULSE</span><h3>{selected==="all"?"Your watchlist":selected}</h3><p>{recent.length} recent filings shown · {analyzed.length} analyzed with Groq</p></div><div className="pulse-counts"><span><b>{positive}</b> positive</span><span><b>{negative}</b> negative</span><span><b>{analyzed.length-positive-negative}</b> mixed / neutral</span></div><small>Counts cover the filings shown below and describe filing content, not share-price movement.</small></div>}
    <div className="section-title filings-title"><div><h2>Corporate filings</h2><p>Latest announcements from your selected companies.</p></div><select aria-label="Filter by company" value={selected} onChange={e=>setSelected(e.target.value)}><option value="all">All companies</option>{data?.watchlist.map(c=><option key={c.symbol} value={c.symbol}>{c.symbol}</option>)}</select></div>
    <div className="feed-status"><i className={data?.feed?.status.startsWith("Connected")?"connected":""}/>{data?.feed?.status||"Waiting for first feed check"} <span>{/^(Connected|Partial)/.test(data?.feed?.status||"")?"NSE checks every minute · dashboard refreshes every 30 seconds":"Feed checks unavailable · dashboard refreshes every 30 seconds"}</span></div>
    {data?.members?.some(m=>m.email===data.account&&m.role==="owner")&&<form className="invite-form" onSubmit={async e=>{e.preventDefault();if(await action("/api/invite",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:invitation})},"invite")){setInvitation("");setMessage("Invitation added. Ask them to sign in with that email.")}}}><label htmlFor="invite-email">Invite family member</label><input id="invite-email" type="email" required placeholder="father@example.com" value={invitation} onChange={e=>setInvitation(e.target.value)}/><button disabled={busy==="invite"}>Add email</button></form>}
    <form className="alert-settings" onSubmit={async e=>{e.preventDefault();if(await action("/api/settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({telegram_chat_id:chatId,telegram_alerts:telegramAlerts,email_alerts:emailAlerts})},"settings"))setMessage("Alert preferences saved.")}}><h2>Alert delivery</h2><p>Material positive or negative Groq findings trigger alerts after the next successful feed check. Delivery requires configured server keys.</p><label><input type="checkbox" checked={emailAlerts} onChange={e=>setEmailAlerts(e.target.checked)}/> Email this account</label><label><input type="checkbox" checked={telegramAlerts} onChange={e=>setTelegramAlerts(e.target.checked)}/> Telegram</label><input aria-label="Telegram chat ID" value={chatId} onChange={e=>setChatId(e.target.value)} placeholder="Telegram chat ID"/><button disabled={busy==="settings"}>Save preferences</button><small>Start your Telegram bot, then enter your chat ID. The bot token stays on the server.</small></form>
    {!!data?.deliveries?.length&&<div className="delivery-line">Latest alert delivery: {data.deliveries[0].channel} · {data.deliveries[0].status} · {fmt(data.deliveries[0].attempted_at)} IST</div>}
    {error&&<div className="notice error">{error}</div>}{message&&<div className="notice" role="status">{message}<button onClick={()=>setMessage("")} aria-label="Dismiss"><X size={15}/></button></div>}
    <div className="filing-list">{filtered.map(f=>{const a=note(f.analysis);return <button key={f.id} className="filing" onClick={()=>open(f)}><i className={f.read_at?"read":""}/><div><div className="row-head"><strong>{f.symbol}</strong><span className="category-tag">{f.category||"Announcement"}</span><span className={`tag ${a?.sentiment||"new"}`}>{a?.sentiment||"New filing"}</span></div><h3>{headline(f)}</h3><p>{a?.summary||f.description||"Open the original announcement for details."}</p></div><small>{fmt(f.published_at)} <ExternalLink size={14}/></small></button>})}{!filtered.length&&<div className="empty"><FileText size={29}/><h3>{data?.watchlist.length?"No matching filings yet":"Your feed starts with a company"}</h3><p>{data?.watchlist.length?"New announcements appear when NSE lists a company you follow. Check the feed status above.":"Search and add a company above to monitor published filings."}</p></div>}</div>
    <p className="footnote">Filings are matched from NSE’s public announcement feed. Verify each item at its source. AI research notes are not personalized investment recommendations.</p></main></div>
    {active&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setActive(null)}}><section className="drawer" role="dialog" aria-modal="true" aria-label="Filing details"><header><span>FILING DETAILS</span><button onClick={()=>setActive(null)} aria-label="Close"><X size={20}/></button></header><div className="drawer-body"><div className="drawer-company"><span className="monogram">{active.symbol.slice(0,2)}</span><strong>{active.symbol}</strong></div><h2>{headline(active)}</h2><small>{active.category||"Announcement"} · Published {fmt(active.published_at)} IST</small><a className="source-link" href={active.url} target="_blank" rel="noopener noreferrer">View original NSE filing <ExternalLink size={16}/></a><hr/><h3>SOURCE DESCRIPTION</h3><p>{active.description||"The feed did not include a description. Read the original filing for details."}</p><hr/><div className="ai-heading"><Sparkles size={18}/> AI research note</div>{note(active.analysis)?<div className="analysis"><div className="evidence">Evidence: {note(active.analysis)?.evidence}</div><h4>What happened</h4><p>{note(active.analysis)?.summary}</p><h4>Why it may matter</h4><p>{note(active.analysis)?.reasoning}</p><h4>What remains uncertain</h4><p>{note(active.analysis)?.uncertainties||"Verify against the original source."}</p><small>Analyzed {fmt(note(active.analysis)?.analyzedAt)} IST</small></div>:<div className="analysis-empty"><p>Ask Groq for a source grounded summary and possible implications.</p><button onClick={()=>analyze(active)} disabled={!!busy}><Sparkles size={16}/>{busy===active.id?"Analyzing...":"Analyze filing"}</button><small>PDF or XBRL/XML text is read when the linked source is accessible. Otherwise analysis uses only the feed headline and description.</small></div>}</div></section></div>}
  </div>
}
